name: Artifact Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: |
          README.md

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: ./downloaded-artifact

    - name: List downloaded files
      run: ls -al ./downloaded-artifact

    - name: download
      run: wget https://github.com/lou-lan/test-action/releases/download/v1/egressgateway-agent.tar

    - name: ls
      run: pwd && ls -l

    - name: scan image
      uses: aquasecurity/trivy-action@0.24.0
      with:
        input: egressgateway-agent.tar
        scan-type: 'image'
        severity: 'CRITICAL,HIGH'      